{
    "id": "CWE-248",
    "name": "Uncaught Exception",
    "href": "AIP/quality-standards/CWE/items/CWE-248",
    "url": "https://cwe.mitre.org/data/definitions/248.html",
    "description": "An exception is thrown from a function, but it is not caught.",
    "count": 0,
    "qualityRules": null
}
