{
    "id": "CWE-248",
    "name": "Uncaught Exception",
    "href": "Echo/quality-standards/ISO-5055/items/CWE-248",
    "url": "https://cwe.mitre.org/data/definitions/248.html",
    "description": "An exception is thrown from a function, but it is not caught.",
    "isoPatterns": [
        {
            "name": "ASCQM Catch Exceptions"
        }
    ],
    "count": 0,
    "qualityRules": null
}
