[
    {
        "id": 678,
        "name": "Never throw an exception from a Destructor",
        "href": "AIP/quality-rules/678",
        "critical": false,
        "weight": 5,
        "technologyNames": [
            "C++"
        ]
    },
    {
        "id": 7824,
        "name": "Avoid directly throwing instance of Exception class",
        "href": "AIP/quality-rules/7824",
        "critical": false,
        "weight": 5,
        "technologyNames": [
            "C#",
            "JEE",
            "VB.NET"
        ]
    },
    {
        "id": 8412,
        "name": "\"CX_ROOT\" should not be used in TRY .. CATCH.. ENDTRY block",
        "href": "AIP/quality-rules/8412",
        "critical": false,
        "weight": 5,
        "technologyNames": [
            "ABAP"
        ]
    },
    {
        "id": 1020540,
        "name": "Avoid using $http success and error function",
        "href": "AIP/quality-rules/1020540",
        "critical": false,
        "weight": 5,
        "technologyNames": [
            "HTML5"
        ]
    },
    {
        "id": 1065026,
        "name": "Ensure exception objects are always caught by reference (C++)",
        "href": "AIP/quality-rules/1065026",
        "critical": false,
        "weight": 5,
        "technologyNames": [
            "C++"
        ]
    }
]
