[
    {
        "id": 678,
        "name": "Never throw an exception from a Destructor",
        "href": "AIP/quality-rules/678",
        "critical": true,
        "technologyNames": [
            "C++"
        ]
    },
    {
        "id": 4656,
        "name": "Avoid declaring an exception in the method signature and not throwing it",
        "href": "AIP/quality-rules/4656",
        "critical": false,
        "technologyNames": [
            "JEE"
        ]
    },
    {
        "id": 7824,
        "name": "Avoid directly throwing instance of Exception class",
        "href": "AIP/quality-rules/7824",
        "critical": true,
        "technologyNames": [
            "C#",
            "JEE",
            "VB.NET"
        ]
    },
    {
        "id": 8412,
        "name": "\"CX_ROOT\" should not be used in TRY .. CATCH.. ENDTRY block",
        "href": "AIP/quality-rules/8412",
        "critical": true,
        "technologyNames": [
            "ABAP"
        ]
    },
    {
        "id": 1020450,
        "name": "Ensure catching Javascript error in React components",
        "href": "AIP/quality-rules/1020450",
        "critical": false,
        "technologyNames": [
            "HTML5"
        ]
    },
    {
        "id": 1020856,
        "name": "Ensure catching Typescript error in React components",
        "href": "AIP/quality-rules/1020856",
        "critical": false,
        "technologyNames": [
            "HTML5"
        ]
    },
    {
        "id": 1065026,
        "name": "Ensure exception objects are always caught by reference (C++)",
        "href": "AIP/quality-rules/1065026",
        "critical": false,
        "technologyNames": [
            "C++"
        ]
    }
]
